baseURL = 'https://lbertrand417.github.io/IGD301-blog'
languageCode = 'en-us'
title = 'IGD301 - Blog'
theme = "blist"
publishDir = "docs"

contentDir = "content" #English
staticDir = ['static']

# Enable emoji
enableEmoji = true

[params]
  introTitle = "Hey! I'm Lauriane Bertrand"
  introSubtitle = "This blog will present my work during the IGD301 course of Telecom Paris. Hope you enjoy!"

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Lauriane Bertrand · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I'm an engineer student in computer graphics"
  linkedin = "https://www.linkedin.com/in/lauriane-b-6b1064152/"
  github = "https://github.com/lbertrand417"

[[menu.main]]
  name = "Blog"
  url = "blog"
  weight = 1

[[menu.main]]
   name = "About"
   url = "page/about/"
   weight = 2

[[menu.main]]
   name = "Tags"
   url = "tags"
   weight = 3

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true