baseURL = 'https://lbertrand417.github.io/IGD301-blog'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "blist"
publishDir = "docs"

contentDir = "content" #English

[params]
  introTitle = "Hey! I'm Katheryn Fox"
  introSubtitle = "26 y/o junior developer who enjoys social card games, blogging and painting"
  introPhoto = "/picture.jpg"

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  xing = "https://www.xing.com/profile/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"

[[menu.main]]
  name = "Blog"
  url = "blog"
  weight = 1

[[menu.main]]
   name = "About"
   url = "page/about/"
   weight = 2

[[menu.main]]
   name = "Tags"
   url = "tags"
   weight = 3

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true